#==================================================================
#Tabela que contém os dados das pessoas que tem acesso ao sistema =
#==================================================================
CREATE TABLE MF_ACESSO(
	COD_LOGIN    BIGINT        PRIMARY KEY AUTO_INCREMENT,
    NOM_OPERADOR VARCHAR(200)  NOT NULL,
    EMAIL		 VARCHAR(200)  		   ,
    LOGIN	     VARCHAR(50)   NOT NULL,
    NASCIDO	     DATE		   NOT NULL,
    SEXO	     ENUM('F','M')
    COMMENT 'F-FEMININO / M-MASCULINO' ,
    SENHA		 VARCHAR(1000)		   ,
    COD_ACESSO	 BIGINT
);

ALTER TABLE    MF_ACESSO
ADD CONSTRAINT UN_MF_ACESSO_EMAIL
UNIQUE(EMAIL);

ALTER TABLE    MF_ACESSO
ADD CONSTRAINT UN_MF_ACESSO_LOGIN
UNIQUE(LOGIN);

ALTER TABLE    MF_ACESSO
ADD CONSTRAINT FK_MF_TIPO_ACESSO_MF_ACESSO
FOREIGN KEY    (COD_ACESSO)
REFERENCES 	   MF_TIPO_ACESSO(COD_ACESSO);

#=============================================================
#Tabela de auditoria =========================================
#=============================================================

CREATE TABLE MF_ACESSO_AUDITORIA(
	COD_AUDITORIA BIGINT            PRIMARY KEY AUTO_INCREMENT,
	COD_LOGIN    BIGINT        ,
    NOM_OPERADOR VARCHAR(200)  ,
    EMAIL		 VARCHAR(200)  ,
    LOGIN	     VARCHAR(50)   ,
    NASCIDO	     DATE		   ,
    SEXO	     ENUM('F','M')
    COMMENT 'F-FEMININO / M-MASCULINO' ,
    SENHA		 VARCHAR(1000)		   ,
    COD_ACESSO	 BIGINT				   ,
    FLG_ACAO	  ENUM('I','U','D') NOT NULL
    COMMENT 'I-INSERT / U-UPDATE / D-DELETE',
    LOGIN_AU		  VARCHAR(30) 		NOT NULL,
    DAT_AUDITORIA TIMESTAMP   		NOT NULL
);

#=============================================================
#Trigger =====================================================
#=============================================================

DELIMITER !!
CREATE TRIGGER TG_MF_ACESSO_I
AFTER INSERT ON MF_ACESSO FOR EACH ROW
BEGIN
	INSERT INTO MF_ACESSO_AUDITORIA
    (COD_LOGIN,NOM_OPERADOR,EMAIL,LOGIN,NASCIDO,SEXO,SENHA,COD_ACESSO,FLG_ACAO,LOGIN_AU,DAT_AUDITORIA)
    VALUES
    (NEW.COD_LOGIN,NEW.NOM_OPERADOR,NEW.EMAIL,NEW.LOGIN,NEW.NASCIDO,NEW.SEXO,NEW.SENHA,NEW.COD_ACESSO,'I',USER,NOW());
END!!

CREATE TRIGGER TG_MF_ACESSO_U
AFTER UPDATE ON MF_ACESSO FOR EACH ROW
BEGIN
	DECLARE NOM_OPERADOR VARCHAR(200)  DEFAULT NULL;
	DECLARE EMAIL 	     VARCHAR(200)  DEFAULT NULL;
	DECLARE LOGIN 	     VARCHAR(50)   DEFAULT NULL;
	DECLARE NASCIDO 	 DATE          DEFAULT NULL;
	DECLARE SEXO 	     ENUM('F','M') DEFAULT NULL;
	DECLARE SENHA 	     VARCHAR(1000) DEFAULT NULL;
	DECLARE COD_ACESSO 	 BIGINT        DEFAULT NULL;
    
    IF NEW.NOM_OPERADOR != OLD.NOM_OPERADOR THEN SET NOM_OPERADOR := OLD.NOM_OPERADOR; END IF;
    IF NEW.EMAIL 	   != OLD.EMAIL         THEN SET EMAIL        := OLD.EMAIL;        END IF;
    IF NEW.NASCIDO 	   != OLD.NASCIDO       THEN SET NASCIDO      := OLD.NASCIDO;      END IF;
    IF NEW.SEXO 	   != OLD.SEXO          THEN SET SEXO         := OLD.SEXO;         END IF;
    IF NEW.SENHA 	   != OLD.SENHA         THEN SET SENHA        := OLD.SENHA;        END IF;
    IF NEW.COD_ACESSO  != OLD.COD_ACESSO    THEN SET COD_ACESSO   := OLD.COD_ACESSO;   END IF;
    
	INSERT INTO MF_ACESSO_AUDITORIA
    (COD_LOGIN,NOM_OPERADOR,EMAIL,LOGIN,NASCIDO,SEXO,SENHA,COD_ACESSO,FLG_ACAO,LOGIN_AU,DAT_AUDITORIA)
    VALUES
    (OLD.COD_LOGIN,NOM_OPERADOR,EMAIL,LOGIN,NASCIDO,SEXO,SENHA,COD_ACESSO,'U',USER,NOW());
END!!

CREATE TRIGGER TG_MF_ACESSO_D
AFTER DELETE ON MF_ACESSO FOR EACH ROW
BEGIN
	INSERT INTO MF_ACESSO_AUDITORIA
    (COD_LOGIN,NOM_OPERADOR,EMAIL,LOGIN,NASCIDO,SEXO,SENHA,COD_ACESSO,FLG_ACAO,LOGIN_AU,DAT_AUDITORIA)
    VALUES
    (OLD.COD_LOGIN,OLD.NOM_OPERADOR,OLD.EMAIL,OLD.LOGIN,OLD.NASCIDO,OLD.SEXO,OLD.SENHA,OLD.COD_ACESSO,'D',USER,NOW());
END!!

DELIMITER ;
